name: core_package
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  auto_route: ^3.2.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  dartz: ^0.10.1
  dots_indicator: ^2.0.0
  easy_localization: ^3.0.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  flutter_gen: ^4.1.5
  flutter_screenutil: ^5.1.0
  flutter_share: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.1
  image_picker: ^0.8.4+4
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  json_annotation: ^4.4.0
  jwt_decoder: ^2.0.1
  percent_indicator: ^3.4.0
  permission_handler: ^8.3.0
  pull_to_refresh: ^2.0.0
  readmore: ^2.1.0
  retrofit: ^3.0.1
  shared_preferences: ^2.0.12
  shimmer: ^2.0.0
  visibility_detector: ^0.2.2
  share_plus: ^3.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.5
  flutter_native_splash: ^1.3.3
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.0
  logger: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/general/